extensions: {}
cabal-file: project.cabal
extra-packages: ''
version: 1
environment: ghc-7.4.2-stable-13.09
module-template: ! 'module MODULE_NAME where

'
ghc-args: []
modules:
  World:
    filename: src/World.hs
  Physics:
    filename: src/Physics.hs
  Main(src/Main.hs):
    filename: src/Main.hs
  Json:
    filename: src/Json.hs
  Test.Main:
    filename: src/Test/Main.hs
  Simulation:
    filename: src/Simulation.hs
